export const residencies = [
        {
            title: "When should you trust AI—and when should you trust yourself?",
            description: "When should you trust AI—and when should you trust yourself?",
            category: "Judgment",
            icon: "psychology",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/1.png"],
        },
        {
            title: "What is money when value itself is unstable?",
            description: "What is money when value itself is unstable?",
            category: "Stability",
            icon: "payments",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/2.png"],
        },
        {
            title: "Can you notice stress before it takes over?",
            description: "Can you notice stress before it takes over?",
            category: "Regulation",
            icon: "monitor_heart",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/3.png"],
        },
        {
            title: "How much digital interaction do you actually need?",
            description: "How much digital interaction do you actually need?",
            category: "Boundaries",
            icon: "devices_off",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/4.png"],
        },
        {
            title: "Do your values change when the world does?",
            description: "Do your values change when the world does?",
            category: "Integrity",
            icon: "balance",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/5.png"],
        },
        {
            title: "What would you say—if you didn't have more time?",
            description: "What would you say—if you didn't have more time?",
            category: "Completion",
            icon: "mail",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/6.png"],
        },
        {
            title: "Who are you when no one is watching?",
            description: "Who are you when no one is watching?",
            category: "Identity",
            icon: "person_search",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/7.png"],
        },
        {
            title: "What happens when you say less—but mean more?",
            description: "What happens when you say less—but mean more?",
            category: "Precision",
            icon: "record_voice_over",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/8.png"],
        },
        {
            title: "When does action matter more than expression?",
            description: "When does action matter more than expression?",
            category: "Execution",
            icon: "bolt",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/9.png"],
        },
        {
            title: "Do you want to leave the city—or just your current life?",
            description: "Do you want to leave the city—or just your current life?",
            category: "Positioning",
            icon: "location_city",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/10.png"],
        },
        {
            title: "Why does writing reveal what thinking cannot?",
            description: "Why does writing reveal what thinking cannot?",
            category: "Clarity",
            icon: "edit_note",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/11.png"],
        },
        {
            title: "Can your knowledge system actually think with you?",
            description: "Can your knowledge system actually think with you?",
            category: "Structure",
            icon: "account_tree",
            images: ["https://lidbucketnew.s3.ap-south-1.amazonaws.com/TheSilentClub/Experiences/Residency/12.png"],
        },
    ];
